### ISSUE TITLE
Research Paper Outline

### ISSUE THREAD

**Issue by neil-unomaha** [neil-unomaha/CIF_CYBR_8950#26]

**Comment by skyemakable** [comment]
Draft Research Paper Outline

- Introduction
  - Explain what CIF is and its goals
- Project Goals
  - Explain what CIF does now to retrieve information from Palo Alto
    - Share diagram and details on how it works at this time
      - Cron job is ran once a day to retrieve information from Palo Alto hardware, and then relayed to CIF
    - Explain how we aim to work with Palo Alto API and CIF to make the information pulling from Palo Alto hardware automatic
      - Hopefully pull information from PA every 15 minutes

- Questions/Considerations

  - When the cron job is run, how much information, on average, is being sent to CIF?
  - If we pull and send information between the PA and CIF every 15 minutes, how much information is being sent? Does it use up a lot of resources to send the information every 15 minutes?
  - Etc.

- CIF Research and Setup
  - ­­­~~Details on where the Documentation was located?~~
    - ~~Feedback from documentation review~~
      - ~~Is it up to date? Easy to follow? Etc.~~
    - Install CIF on Ubuntu 16.04 server VMs to first familiarizeourselves with CIF
    - Details on the requirements of CIF installation
    - Roadblocks and other notes from installing CIF that are worth mentioning
      - How were the roadblocks mitigated?
      - What else stuck out and why?

- Palo Alto API Research and Implementation
  - Details on researching Palo Alto Documentation
    - Was it up to date? Easy to follow? What resources wereavailable?
  - Details on getting access to Palo Alto API
    - Get it from Brian somehow? Palo Alto?
      - ~~Details on this pending~~
  - Details on setting up Palo Alto to work with CIF
    - What was required?
    - What issues/roadblocks did we face?
- Putting PA API and CIF together
  - TBD

- Summary of findings

- Conclusion

-----

- Note: Many sections include roadblocks/issues that arose. We may want to dedicate a Roadblock/Issue section to this.

- Note: Don't use a converter from Word to Markdown because you're gonna have a bad time.

**Comment by skyemakable** [comment]
Notes about research paper outline
-----

Introduction
- first paragraph problem context
- what has been done about problem context
- in this paper we plan to do blah blah blah and relay back to gaps that was set up in problem context
- rest of the paper will flow as yadda

background/literature review
- here are the major areas of research that are relevant to this problem
- touch on top level categories - synthesize around the authors you found. Try to make meaningful picture between all the authors to characterize the space and draw from all the references we looked through
- mainly conducting experiment, but can point to something like threat vector mitigation, some may have tried this but we speak to it better
(CIF could be in background but also it's own section)

methodology
- explaining what you did and maybe talk about the solution
- or just the experiment setup

results
- can mostly be heading for now

conclusion

**Comment by neil-unomaha** [comment]
# Notes from meeting with Dr. Hale:

## Rough Format of Abstract (500 words or less)

* two sentences (characterize problem)
* two sentences (what others are doing)
* two sentences (what we are doing)
* two sentences (findings)

## Rough Format of Outline:

* Introduction
* Literature Review
  * Major areas of research relevant and what they have done: CIF, Threat intelligence, Threat vector mitigation
* Methodology
  * What we did
* Results and Findings
* Conclusion

**Comment by neil-unomaha** [comment]
- Brief overview of the threat landscape online (stats for universities, enterprises, citation needed)
- Enterprises and Universities are protecting their networks with xyz (citation needed)
  - cost factor for these various protections (citation needed)
- One of the cheapest security mechanisms is utilizing threat intelligence (citation needed)
  - describe threat intelligence
- CIF is one such form of threat intelligence
  - background on CIF
- The University of Nebraska’s utilization of the CIF framework
  - University coalition of threat feeds
- The issue of pulling in external threat feeds into existing intrusion detection systems
- Our research questions and what we hope to solve (reference our research question)

**Comment by neil-unomaha** [comment]
8dc0bef5631723f336189227f0a2a16fb6613682
